
import pandas as pd
import json
import sys
import os
from pathlib import Path
import numpy as np
import faiss
import torch
from covertree import CoverTree
import hashlib
from collections import defaultdict
from statistics import mean, median, quantiles

# Try to import the config file generated by CMake
try:
    from covertree_config import USE_GPU, USE_OPENAI_EMBEDDINGS
except ImportError:
    USE_GPU = False
    USE_OPENAI_EMBEDDINGS = False

# Optional imports for online embeddings
try:
    import openai
    import tenacity
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

def hash_vec(v, places=1):
    fmt = "{{:+.{}E}}".format(places)
    vec = np.array(v).astype('float64')
    vec = np.round(vec, decimals=places)
    vec_string = "".join([fmt.format(float(x)) for x in vec]).encode("utf-8")
    return hashlib.sha256(vec_string).hexdigest()

def enum_hash_vecs(arr, places=1):
    hashed_vecs = [hash_vec(v, places=places) for v in arr]
    enumd_hashes = list(enumerate(hashed_vecs))
    return dict(enumd_hashes)

def map_hashed_vecs_to_enums(enumd_hashed_vecs):
    hashed_vecs_to_enum = defaultdict(set)
    for i,hv in enumd_hashed_vecs.items():
        hashed_vecs_to_enum[hv].add(i)
    return hashed_vecs_to_enum

def gen_test_data(N=100):
    '''Generate an N by N square array for test data to sanity check cover tree implementation.'''
    row = [float(i) for i in range(N)]
    arr = np.array(row).reshape(1,N)
    for i in range(1,N):
        row.append(row.pop(0))
        r = np.array(row).reshape(1,N)
        arr = np.append(arr, r, axis=0)
    return arr

def gen_test_data_dup(N=100, duplication=3):
    '''Generate an duplication*N by N array to sanity check cover tree implemenation.'''
    arr = gen_test_data(N)
    for i in range(1,duplication):
        arr = np.append(arr, gen_test_data(N), axis=0)
    return arr

def get_openai_embeddings(text_list, api_key, endpoint, model, dimensions=None, max_retries=6):
    """
    Get embeddings from an OpenAI-compatible API with retry logic.
    
    Args:
        text_list: List of strings to embed
        api_key: API key for the service
        endpoint: Base URL for the embedding endpoint (e.g., "https://api.openai.com/v1/embeddings")
        model: Model name to use for embeddings
        dimensions: Optional dimensions parameter (for models that support it)
        max_retries: Maximum number of retry attempts
    
    Returns:
        numpy array of shape (len(text_list), embedding_dim)
    """
    if not OPENAI_AVAILABLE:
        raise ImportError(
            "OpenAI and tenacity packages are required for online embeddings. "
            "Install them with: pip install openai tenacity"
        )
    
    # Configure the OpenAI client
    client = openai.OpenAI(
        api_key=api_key,
        base_url=endpoint.rstrip('/v1/embeddings') if endpoint.endswith('/v1/embeddings') else endpoint
    )
    
    # Define retry strategy
    wait_strategy = tenacity.wait_exponential(multiplier=1, min=2, max=30)
    retry_strategy = tenacity.retry_if_exception_type((
        openai.RateLimitError,
        openai.APIConnectionError,
        openai.InternalServerError,
        openai.APITimeoutError
    ))
    
    @tenacity.retry(
        stop=tenacity.stop_after_attempt(max_retries),
        wait=wait_strategy,
        retry=retry_strategy,
        reraise=True
    )
    def _get_embeddings_batch(batch):
        # Prepare request
        kwargs = {
            "input": batch,
            "model": model,
            "encoding_format": "float"
        }
        if dimensions is not None:
            kwargs["dimensions"] = dimensions
            
        response = client.embeddings.create(**kwargs)
        return np.array([item.embedding for item in response.data])
    
    # Process in batches to avoid API limits
    batch_size = 1000  # Safe batch size for most APIs
    all_embeddings = []
    
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        try:
            batch_embeddings = _get_embeddings_batch(batch)
            all_embeddings.append(batch_embeddings)
        except Exception as e:
            print(f"Error processing batch {i//batch_size + 1}: {str(e)}", file=sys.stderr)
            raise
    
    if not all_embeddings:
        return np.empty((0, 0))
    
    return np.vstack(all_embeddings)

# Conditional data generation
if USE_OPENAI_EMBEDDINGS:
    # Use OpenAI embeddings
    # Define the texts to embed
    texts = [
        "The quick brown fox jumps over the lazy dog.",
        "Embedding models map text to high-dimensional vectors.",
        "Machine learning is fascinating.",
        "OpenAI provides powerful API for text embeddings.",
        "This is a sample text for embedding."
    ]

    # Get OpenAI API key from environment
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("Please set the OPENAI_API_KEY environment variable")

    endpoint = os.getenv("OPENAI_ENDPOINT", "https://api.openai.com/v1/embeddings")
    model = os.getenv("OPENAI_MODEL", "text-embedding-3-small")

    # Get embeddings
    embeddings = get_openai_embeddings(texts, api_key, endpoint, model)

    # Normalize embeddings to unit length (for cosine similarity via inner product)
    # Note: OpenAI's text-embedding-3 models are already normalized, but we do it again to be safe.
    embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)
    # Convert to float32 for consistency with synthetic data and FAISS
    embeddings = np.float32(embeddings)
    d = embeddings.shape[1]
else:
    # Original synthetic data
    np.random.seed(42)
    d = 128
    N = 1000
    embeddings = np.random.randn(N, d).astype(np.float32)
    embeddings /= np.linalg.norm(embeddings, axis=1, keepdims=True)

# Build the CoverTree from the embeddings matrix
ct = CoverTree.from_matrix(embeddings)

# Prepare embeddings for FAISS: ensure they are contiguously arranged in memory
embeddings = np.ascontiguousarray(embeddings, dtype=np.float32)

# Build the FAISS index
if USE_GPU and torch.cuda.is_available():
    gpu_id = 0
    res = faiss.StandardGpuResources()
    cfg = faiss.GpuIndexFlatConfig()
    cfg.useFloat16 = False
    cfg.device = gpu_id
    index = faiss.GpuIndexFlatIP(res, d, cfg)
else:
    index = faiss.IndexFlatL2(d)

index.add(embeddings)

# Dump cover tree into JSON and create Python data structures
ct_json = ct.dumps()
ct_data = json.loads(ct_json)

node_data = [{"id":n["id"],
               "level":n["level"],
               "covdist":n["covdist"],
               "sepdist":n["sepdist"],
               "rootdist":n["rootdist"]} for n in ct_data["nodes"]]

node_points = {n["id"]:n["point"] for n in ct_data["nodes"]}

n2hv = {id:hash_vec(v) for (id,v) in node_points.items()}
# assert(set(n2hv.values()) == set(e2hv.values()))

def node2enums(id, np=node_points, hv2e=hv2e):
    return hv2e[hash_vec(np[id])]

# Tree level given node
node_level = {n["id"]:n["level"] for n in node_data}

# Nodes associated with each tree level
level_nodes = defaultdict(set)
for k,v in node_level.items():
    level_nodes[v].add(k)

# Number of nodes associated with each tree level
level_count = {k:len(v) for (k,v) in level_nodes.items()}

# Number of children associated with each node
children = [(ln["parent"], ln["child"]) for ln in ct_data["links"]]
node_children = defaultdict(set)
for p,c in children:
    node_children[p].add(c)

root_dist = [(n['id'], n['level'], n['rootdist']) for n in node_data]
root_dist_mean = mean([n[2] for n in root_dist])
root_dist_median = median([n[2] for n in root_dist])
root_dist_sorted = sorted(root_dist, key=lambda n:n[2], reverse=True)

def k_outliers(k):
    return {n for (n,_,_) in root_dist_sorted[0:k]}

# map node id to index point query
id2q = {id: np.reshape(np.float32(p), (1,d)) for (id,p) in node_points.items()}

# map map node ID to original dataframe rows
def id2rows(id, k=5, t=1):
    if not id in id2q:
        return set()
    else:
        D,I = index.search(id2q[id], k)
        n = I.tolist()[0]
        d = D.tolist()[0]
        rows = []
        for i in range(len(d)):
            if d[i] < t:
                rows.append(n[i])
        return set(rows)

# map original dataframe row to item name
row2name = {item[0]:item[1] for item in enumerate(list(df.transpose().columns))}

def id2names(id,k):
    return {row2name[r] for r in id2rows(id,k)}

def dump_id_names(k=5, t=1):
    for id in id2q.keys():
        for r in id2rows(id,k,t):
            print(id,row2name[r])

def parent_child_graph(fname):
    head = """
digraph {
        layout=twopi
        overlap=prism
        overlap_scaling=35
    """

    A = 3

    with open(fname, "w") as fout:
        top_B = k_outliers(2*A)
        top_A = k_outliers(A)
        next_A = top_B - top_A

        print(head, file=fout)
        print("\t{} [style=filled, fillcolor=\"blue\"]".format(0), file=fout)

        for outlier in top_A:
            print("\t{} [style=filled, fillcolor=\"red\"]".format(outlier), file=fout)

        for outlier in next_A:
            print("\t{} [style=filled, fillcolor=\"purple\"]".format(outlier), file=fout)

        for (p,c) in children:
            print("\t{} -> {}".format(p,c), file=fout)

        print("}", file=fout)

def parent_child_graph_2():
    head = """
digraph {
        layout=twopi
        overlap=prism
        overlap_scaling=35
    """
    print(head)
    for (p,c) in children:
        print("\t{} -> {}".format(p,c))
    print("}")
